### ISSUE TITLE
Add Inkscape to Image

### ISSUE THREAD

**Issue by Babalion** [Tuetenk0pp/sharelatex-full#1]
**Is your feature request related to a problem? Please describe.**
When using the package `svg` it is not possible to include svg images because an inkscape-installation is missing.

**Describe the solution you'd like**
Please add `apt install inkscape` to your Dockerfile.

**Comment by Tuetenk0pp** [comment]
Hi @Babalion, I would happily do that. Can you provide a MWE that I can test with?

**Comment by Babalion** [comment]
Here is an overleaf-project zip as MWE:
[Inkscape package on Overleaf.zip](https://github.com/Tuetenk0pp/sharelatex-full/files/9181285/Inkscape.package.on.Overleaf.zip)
