### ISSUE TITLE
Biber not working

### ISSUE THREAD

**Issue by Linki303** [Tuetenk0pp/sharelatex-full#18]
Hi, 
thanks for the grate docker image. It makes a lot of things easier. I have copied a latex file from overleaf.com to my own sharelatex with your image. But I found one issue. 
I always get this error:
Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                output
(biblatex)                and rerun LaTeX afterwards.

This error I don´t get on overleaf.com Do you have any idea what I have to do, to solve that problem?

**Comment by Tuetenk0pp** [comment]
- Try to delete all intermediate files on both overleaf.com and your instance and see if the code compiles. If it doesn't compile on overleaf.com, something could be wrong with your code.
- Did you exactly match the compile settings?
- If the document still doesn't compile it would be helpful if you posted the full logs and your code so that I can take a look.

**Comment by Linki303** [comment]
Hi,
I have checked with a template of my document. It is attached to here. The problem occurs in the docker installation but not occurs in overleaf.com. I have also attached the logs.
[output(docker).log](https://github.com/Tuetenk0pp/sharelatex-full/files/11229529/output.docker.log)
[output (overleaf).log](https://github.com/Tuetenk0pp/sharelatex-full/files/11229530/output.overleaf.log)
[m118-berichtvorlage-master-latex (1).zip](https://github.com/Tuetenk0pp/sharelatex-full/files/11229531/m118-berichtvorlage-master-latex.1.zip)
I hope you can find out the problem.

Thanks a lot
Martin

**Comment by Tuetenk0pp** [comment]
I had a look at it yesterday and can confirm it is some sort of bug, not related to overleaf or texlive. I will try to investigate further. Sometimes in the past, a simple rebuild of the image solved the issue, due to updated packages or similar.

**Comment by Linki303** [comment]
Hi, I find the solution. After running the container I went into the shell with `bin/shell`. There I had to enter ` tlmgr path add`. After a restart of the container and deleting the cache files it is running without error.
Maybe you can do that directly in your original image for all others who are downling your great image.

**Comment by Tuetenk0pp** [comment]
That's great news! I am no texlive expert to be honest, I slowly built this image based on a bunch of web search and trial an error. I will update the image tonight or later tomorrow. Thank you!
