### ISSUE TITLE
How to access the sharelate files and edit without using web-broswer?

### ISSUE THREAD

**Issue by erdiphd** [tuetenk0pp/sharelatex-full#32]
Hi

I can see my project file here 
`sharelatex_data/data/compiles/64db80c90d7f204ff7aa0d60-64db808c0d7f204ff7aa0d32`

![image](https://github.com/tuetenk0pp/sharelatex-full/assets/81103451/23dbb3cb-7fce-4d5b-8cb8-2e840912dede)

I want to edit files from here and see the changes in the web browser. I also would like to use .git in this files.

Unfortunately my changes are not reflected in the web browser. Files are created different user name `www-data`

How can I make changes in my local folder and see them in browser ? 
In addion to that, how can I use .git ?

**Comment by tuetenk0pp** [comment]
I don't know how that can be achieved, sorry. Websearch might help.
