### ISSUE TITLE
The docker-compose.override.yaml file extension (yaml) has changed to yml

### ISSUE THREAD

**Issue by tangruize** [Tuetenk0pp/sharelatex-full#5]
**Describe the bug**
The docker-compose.override.yaml file extension (**yaml**) has changed to **yml**.

**To Reproduce**
1. cd overleaf-toolkit/bin && ./up --detach
2. docker image list
3. REPOSITORY uses sharelatex/sharelatex

**Expected behavior**
The REPOSITORY should be tuetenk0pp/sharelatex-full.
docker-compose.override.yaml doesn't work.

**Comment by Tuetenk0pp** [comment]
Sorry for this bug. I hope you were able to fix it for your installation. Thanks for digging up the problem. I will fix this as soon as I get to it (maybe next week).
