### ISSUE TITLE
ShareLaTeX to Overleaf rebranding

### ISSUE THREAD

**Issue by hzxie** [tuetenk0pp/sharelatex-full#53]
## Steps to Reproduce

1. Use docker-compose following the official instructions https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide
2. Edit `docker-compose.yml`
3. `docker-compose up -d`

## Expected Behaviour

The webpage can be display normally.

## Observed Behaviour

```
  Starting with version 5.0, ShareLaTeX branded file system paths are no
   longer supported as we are migrating to the Overleaf brand.

  Your configuration still uses 1 ShareLaTeX branded paths:
      - /var/lib/sharelatex

  Please update the in-container bind-mount target to refer to the
   Overleaf equivalent:
    - /etc/sharelatex     -> /etc/overleaf
    - /var/lib/sharelatex -> /var/lib/overleaf
    - /var/log/sharelatex -> /var/log/overleaf

  Overleaf toolkit setups:

    github.com/overleaf/toolkit$ bin/upgrade


  Legacy docker compose setups/Horizontal scaling setups:

    before:

      services:
        sharelatex:
          volumes:
           - /my/docker-host/path:/var/lib/sharelatex

    after:

      services:
        sharelatex:
          volumes:
           - /my/docker-host/path:/var/lib/overleaf


  Other deployment methods:

    Adapt the docker compose example or get in touch with support.


  Server Pro: Please update SANDBOXED_COMPILES_HOST_DIR if needed.


  Refusing to startup, exiting in 10s.

------------------------------------------------------------------------
*** An error occurred. Aborting.
*** Shutting down /etc/my_init.d/000_check_for_old_bind_mounts_5.sh (PID 7)...
*** Init system aborted.
*** Killing all processes...
```

## Technical Info

* URL:
* Browser Name and version: Chrome 125.0.6422.76 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Arch Linux
* Signed in as: N/A
* Project and/or file: N/A

**Comment by tuetenk0pp** [comment]
I updated the included compose files to be compatible with overleaf version 5.0.4.

Please note that I don't recommend the use of these files. Use the [Overleaf Toolkit](https://github.com/overleaf/toolkit) instead, as described in the [README](https://github.com/tuetenk0pp/sharelatex-full/blob/master/README.md).
