### ISSUE TITLE
overleaf-toolkit expecting a version number set in config/version

### ISSUE THREAD

**Issue by tsaber** [tuetenk0pp/sharelatex-full#58]
Hi,
thanks a lot for your effort.
I have trouble using your custom image since overleaf now presents a way to enter a custom image in config/overleaf.rc,
but still checks for a non-empty value in config/version.

Could you please help me out?

Gruß

**Comment by tsaber** [comment]
LaTeX Error: Loading a class or package in a group.

I'm also getting this error and I have no idea why.
I deleted all containers and images but my previous login was still valid? somehow the database remained.

**Comment by tuetenk0pp** [comment]
Hello Lukas, glad you were able to resolve the issue.
