### ISSUE TITLE
minted v3

### ISSUE THREAD

**Issue by ThexXTURBOXx** [tuetenk0pp/sharelatex-full#67]
**Describe the bug**
I have to say - I have not tested whether it works or not, but I guess that minted v3 might not work as sharelatex-full is structured currently.

**Additional context**
See the README of minted v3 for further reference on the installation process: https://github.com/gpoore/minted/tree/v3-dev?tab=readme-ov-file#development-status

Also these issues might provide even more insight: https://github.com/overleaf/toolkit/issues/298 and https://github.com/gpoore/minted/issues/401

**Comment by tuetenk0pp** [comment]
Hi, yeah this seems like a future problem. Will do some further reading an try not to produce this bug with the next release 😄

**Comment by ThexXTURBOXx** [comment]
Thanks for the quick fix! :)
However, I seem to have difficulties getting a custom lexer to work.
I think this is because of the new regulations with the `.latexminted_config` file:
In order to enable loading of custom lexers from the Overleaf project (which *could* also be used for arbitrary code execution!!!), `enable_cwd_config` must be set to `true` in the config in either the user home directory or in `TEXMFHOME`.
I don't really know if it's the right way to allow it or to leave it disabled. As it currently stands, custom lexers are disallowed, but maybe they should be allowed?!
This is something that is completely for you @tuetenk0pp to decide, of course :)

**Comment by tuetenk0pp** [comment]
I don't like the idea of enabeling this by default but I see why some people would like the functionallity. Especially if there is a very limited amount of users in that instance. Maybe this could be achieved through a environment variable (`OVERLEAF_MINTED_ENABLE_CWD_CONFIG`) in `config/variables.env` in Overleaf Toolkit.

I would be happy to accept a PR on this as I don't have the time to do it myself right now.
