### ISSUE TITLE
Font Missing in Image Causes Inconsistencies with Web-Based Overleaf

### ISSUE THREAD

**Issue by Mingbo-Lee** [tuetenk0pp/sharelatex-full#72]
**Is your feature request related to a problem? Please describe.**
When using a LaTeX thesis template, I noticed some of the options I configured were not working as expected. Additionally, I observed differences in behavior between the image version and the web-based Overleaf. Upon investigating the issue, I found that it was caused by incomplete font support in your image, such as the absence of Times New Roman. By manually adding the missing fonts and recompiling the LaTeX document, I was able to resolve the problem I encountered.

**Describe the solution you'd like**
Thank you very much for your work; I mean no offense.  

I believe that you and other users would expect the "full" in your image's name to indicate functionality and behavior as close as possible to the web-based Overleaf (excluding paid features). However, the current issue with missing fonts significantly affects the user experience.  

In light of this, I suggest exploring free font download links or including the necessary fonts directly in the repository. Additionally, during the Dockerfile setup, you could incorporate steps to add these fonts. I believe that doing so would make the "full" designation more meaningful and complete.

**Describe alternatives you've considered**
As an alternative, if we cannot implement automatic font downloading or inclusion in the Dockerfile, we should address this issue in the README.md file. It would be helpful to inform users about the problem and suggest a solution. Users can interact with the Docker container to add the required fonts to `/usr/share/fonts/` and then run `fc-cache && fc-list` to ensure the fonts are successfully added.

**Additional context**
Steps to Reproduce:
1. LaTeX Template Link: https://github.com/zoam/xmu-thesis-grd
2. ONLY modify [line](https://github.com/zoam/xmu-thesis-grd/blob/66935128963a3ee01e0d2b101ac08b984e9cd159/demo.tex#L11C1-L11C45)  处 
```tex
\documentclass[twoside, pdf]{xmu-thesis-grd}
```
to 
```tex
\documentclass[master]{xmu-thesis-grd}
```
Then, you will notice that the English title on the thesis cover is missing. Upon checking the error, it turns out that the Times New Roman font is missing.

Thank you for your work. If you need any additional information from me or would like to do anything else, please feel free to contact me.

**Comment by tuetenk0pp** [comment]
I am sorry, this is not something I can fix. Fonts like Times New Roman or Arial are not open-source and are therefore not distributed with the overleaf docker image, nor can I add them to the docker image. You can manually upload the font files to your LaTeX project.

Here's a MWE:

```latex
\documentclass{article}

\usepackage[english]{babel}
\usepackage{fontspec}
\usepackage{blindtext}

\setmainfont{times.ttf}[
    BoldFont=timesbd.ttf,
    ItalicFont=timesi.ttf,
    BoldItalicFont=timesbi.ttf
]

\begin{document}

\blinddocument

\end{document}

```

**Comment by Mingbo-Lee** [comment]
Thank you very much for your reply.
I wonder if you would consider mentioning the missing font in the README as a kind reminder

**Comment by wang1zhen** [comment]
As the sharelatex image is ubuntu based, it is actually possible to add some fonts. For me, I use
```
apt install -y fonts-noto
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
apt install ttf-mscorefonts-installer -y
```
I believe this could be a easy fix, and as the image already contains full texlive which is huge already, additional fonts will not bring a big difference.

**Comment by Mingbo-Lee** [comment]
Hi @wang1zhen  Thank you very much for your work. I recommend adding `apt update` before executing the command

**Comment by wang1zhen** [comment]
Yes, I agree. `apt update` has been executed in the early stage of the dockerfile, therefore I did not include into this part.

**Comment by Mingbo-Lee** [comment]
Thanks for the clarification

**Comment by wang1zhen** [comment]
FYI, I just created another docker image based on this one, you may try wang1zhen/sharelatex-full-with-fonts. Simply replace this in overleaf.rc should work fine!

**Comment by Mingbo-Lee** [comment]
Thank you very much for your effort and your work!
